const produtos = [
  {
    id: "1",
    name: "Camiseta",
    price: "20",
    category: "Roupas",
    size: "M",
    color: "#FFFFFF",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [
      "./camiseta.png",
      "https://example.com/camiseta2.jpg",
      "https://example.com/camiseta3.jpg",
    ],
  },
  {
    id: "2",
    name: "Calça Jeans",
    price: "50",
    category: "Roupas",
    size: "38",
    color: "#0000FF",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: true,
    images: [
      "https://montink.s3.amazonaws.com/nmt/estampas/montink2.lojavirtualnuvem.com.br/Preto_74406858.png",
      "https://example.com/calcajeans2.jpg",
    ],
  },
  {
    id: "3",
    name: "Tênis",
    price: "100",
    category: "Calçados",
    size: "40",
    color: "#00FF00",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [],
  },
  {
    id: "4",
    name: "Boné",
    price: "15",
    category: "Acessórios",
    size: "Único",
    color: "#FF0000",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: false,
    images: [],
  },
  {
    id: "5",
    name: "Camiseta Manga Longa",
    price: "25",
    category: "Roupas",
    size: "M",
    color: "#FFFFFF",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [
      "https://example.com/mangalonga1.jpg",
      "https://example.com/mangalonga2.jpg",
      "https://example.com/mangalonga3.jpg",
    ],
  },
  {
    id: "6",
    name: "Camiseta Regata",
    price: "18",
    category: "Roupas",
    size: "M",
    color: "#FFFFFF",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: false,
    images: [
      "https://example.com/regata1.jpg",
      "https://example.com/regata2.jpg",
    ],
  },
  {
    id: "7",
    name: "Shorts Jeans",
    price: "30",
    category: "Roupas",
    size: "38",
    color: "#0000FF",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [
      "https://example.com/shortsjeans1.jpg",
      "https://example.com/shortsjeans2.jpg",
    ],
  },
  {
    id: "8",
    name: "Tênis Esportivo",
    price: "80",
    category: "Calçados",
    size: "40",
    color: "#00FF00",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: false,
    images: [
      "https://example.com/tenisesportivo1.jpg",
      "https://example.com/tenisesportivo2.jpg",
    ],
  },
  {
    id: "9",
    name: "Boné com Aba Reta",
    price: "20",
    category: "Acessórios",
    size: "Único",
    color: "#FF0000",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [
      "https://example.com/boneabareta1.jpg",
      "https://example.com/boneabareta2.jpg",
    ],
  },
  {
    id: "10",
    name: "Moletom",
    price: "40",
    category: "Roupas",
    size: "M",
    color: "#FFFFFF",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: false,
    images: [
      "https://example.com/moletom1.jpg",
      "https://example.com/moletom2.jpg",
    ],
  },
  {
    id: "11",
    name: "Calça Legging",
    price: "35",
    category: "Roupas",
    size: "M",
    color: "#FFFFFF",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [
      "https://example.com/calcalegging1.jpg",
      "https://example.com/calcalegging2.jpg",
    ],
  },
  {
    id: "12",
    name: "Sandália",
    price: "60",
    category: "Calçados",
    size: "37",
    color: "#00FF00",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: false,
    images: [
      "https://example.com/sandalia1.jpg",
      "https://example.com/sandalia2.jpg",
    ],
  },
  {
    id: "13",
    name: "Boné Snapback",
    price: "25",
    category: "Acessórios",
    size: "Único",
    color: "#FF0000",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [
      "https://example.com/bonesnapback1.jpg",
      "https://example.com/bonesnapback2.jpg",
    ],
  },
  {
    id: "14",
    name: "Camisa Polo",
    price: "30",
    category: "Roupas",
    size: "M",
    color: "#FFFFFF",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: false,
    images: [
      "https://example.com/camisapolo1.jpg",
      "https://example.com/camisapolo2.jpg",
    ],
  }
]

console.log(produtos);



export default produtos;