const produtos = [
  {
    id: "1",
    name: "Camiseta",
    price: "20",
    category: "Roupas",
    size: "M",
    color: "#FFFFFF",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [
      "/./camiseta.png",
      "/./logo.png",
      "/./camiseta.png",
    ],
    description: "Uma camiseta confortável e estilosa para o seu dia a dia.",
  },
  {
    id: "2",
    name: "Calça Jeans",
    price: "50",
    category: "Roupas",
    size: "38",
    color: "#0000FF",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: true,
    images: [
      "/./logo.png",
      "/./logo.png",
    ],
    description: "Uma calça jeans moderna e versátil para diversas ocasiões.",
  },
  {
    id: "3",
    name: "Tênis",
    price: "100",
    category: "Calçados",
    size: "40",
    color: "#00FF00",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [
      "https://example.com/tenis1.jpg",
      "https://example.com/tenis2.jpg",
      "https://example.com/tenis3.jpg",
      "https://example.com/tenis4.jpg",
    ],
    description: "Um tênis confortável e moderno para qualquer ocasião.",
  },
  {
    id: "4",
    name: "Boné",
    price: "15",
    category: "Acessórios",
    size: "Único",
    color: "#FF0000",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: false,
    images: [
      "https://example.com/bone1.jpg",
      "https://example.com/bone2.jpg",
      "https://example.com/bone3.jpg",
    ],
    description: "Um boné estiloso para completar seu visual.",
  },
  {
    id: "5",
    name: "Camiseta Manga Longa",
    price: "25",
    category: "Roupas",
    size: "M",
    color: "#FFFFFF",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [
      "https://example.com/mangalonga1.jpg",
      "https://example.com/mangalonga2.jpg",
      "https://example.com/mangalonga3.jpg",
    ],
    description: "Uma camiseta manga longa confortável para os dias mais frios.",
  },
  {
    id: "6",
    name: "Camiseta Regata",
    price: "18",
    category: "Roupas",
    size: "M",
    color: "#FFFFFF",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: false,
    images: [
      "https://example.com/regata1.jpg",
      "https://example.com/regata2.jpg",
    ],
    description: "Uma camiseta regata ideal para os dias de calor.",
  },
  {
    id: "7",
    name: "Shorts Jeans",
    price: "30",
    category: "Roupas",
    size: "38",
    color: "#0000FF",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [
      "https://example.com/shortsjeans1.jpg",
      "https://example.com/shortsjeans2.jpg",
    ],
    description: "Um shorts jeans confortável e estiloso para qualquer ocasião.",
  },
  {
    id: "8",
    name: "Tênis Esportivo",
    price: "80",
    category: "Calçados",
    size: "40",
    color: "#00FF00",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: false,
    images: [
      "https://example.com/tenisesportivo1.jpg",
      "https://example.com/tenisesportivo2.jpg",
    ],
    description: "Um tênis esportivo confortável e resistente para praticar esportes.",
  },
  {
    id: "9",
    name: "Boné com Aba Reta",
    price: "20",
    category: "Acessórios",
    size: "Único",
    color: "#FF0000",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [
      "https://example.com/boneabareta1.jpg",
      "https://example.com/boneabareta2.jpg",
    ],
    description: "Um boné com aba reta estiloso para compor seu visual urbano.",
  },
  {
    id: "10",
    name: "Moletom",
    price: "40",
    category: "Roupas",
    size: "M",
    color: "#FFFFFF",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: false,
    images: [
      "https://example.com/moletom1.jpg",
      "https://example.com/moletom2.jpg",
    ],
    description: "Um moletom quente e confortável para os dias frios.",
  },
  {
    id: "11",
    name: "Calça Legging",
    price: "35",
    category: "Roupas",
    size: "M",
    color: "#FFFFFF",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [
      "https://example.com/calcalegging1.jpg",
      "https://example.com/calcalegging2.jpg",
    ],
    description: "Uma calça legging confortável para a prática de atividades físicas.",
  },
  {
    id: "12",
    name: "Camisa Social",
    price: "45",
    category: "Roupas",
    size: "M",
    color: "#FFFFFF",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: false,
    images: [
      "https://example.com/camisasocial1.jpg",
      "https://example.com/camisasocial2.jpg",
    ],
    description: "Uma camisa social elegante para ocasiões formais.",
  },
  {
    id: "13",
    name: "Sandália Rasteira",
    price: "30",
    category: "Calçados",
    size: "38",
    color: "#00FF00",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [
      "https://example.com/sandaliarasteira1.jpg",
      "https://example.com/sandaliarasteira2.jpg",
    ],
    description: "Uma sandália rasteira confortável e estilosa para o verão.",
  },
  {
    id: "14",
    name: "Óculos de Sol",
    price: "25",
    category: "Acessórios",
    size: "Único",
    color: "#000000",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: false,
    images: [
      "https://example.com/oculosdesol1.jpg",
      "https://example.com/oculosdesol2.jpg",
    ],
    description: "Óculos de sol com proteção UV para os dias ensolarados.",
  },
  {
    id: "15",
    name: "Vestido",
    price: "60",
    category: "Roupas",
    size: "M",
    color: "#FFFFFF",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [
      "https://example.com/vestido1.jpg",
      "https://example.com/vestido2.jpg",
    ],
    description: "Um vestido elegante para diversas ocasiões.",
  },
  {
    id: "16",
    name: "Chinelo",
    price: "15",
    category: "Calçados",
    size: "38",
    color: "#00FF00",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: false,
    images: [
      "https://example.com/chinelo1.jpg",
      "https://example.com/chinelo2.jpg",
    ],
    description: "Um chinelo confortável para o dia a dia.",
  },
  {
    id: "17",
    name: "Bolsa de Praia",
    price: "35",
    category: "Acessórios",
    size: "Único",
    color: "#FFFF00",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [
      "https://example.com/bolsadepraia1.jpg",
      "https://example.com/bolsadepraia2.jpg",
    ],
    description: "Uma bolsa de praia espaçosa e prática.",
  },
  {
    id: "18",
    name: "Blusa de Frio",
    price: "30",
    category: "Roupas",
    size: "M",
    color: "#FFFFFF",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: false,
    images: [
      "https://example.com/blusadefrio1.jpg",
      "https://example.com/blusadefrio2.jpg",
    ],
    description: "Uma blusa de frio confortável para os dias mais gelados.",
  },
  {
    id: "19",
    name: "Sapato Social",
    price: "70",
    category: "Calçados",
    size: "40",
    color: "#000000",
    createdAt: "2024-03-08",
    isFeatured: true,
    isArchived: false,
    images: [
      "https://example.com/sapatosocial1.jpg",
      "https://example.com/sapatosocial2.jpg",
    ],
    description: "Um sapato social elegante para eventos formais.",
  },
  {
    id: "20",
    name: "Pulseira",
    price: "10",
    category: "Acessórios",
    size: "Único",
    color: "#FF00FF",
    createdAt: "2024-03-08",
    isFeatured: false,
    isArchived: false,
    images: [
      "https://example.com/pulseira1.jpg",
      "https://example.com/pulseira2.jpg",
    ],
    description: "Uma pulseira delicada para complementar seu visual.",
  },
];

console.log(produtos);

interface Produto {
  id: string;
  name: string;
  price: string;
  category: string;
  size: string;
  color: string;
  createdAt: string;
  isFeatured: boolean;
  isArchived: boolean;
  images: string[];
  description: string
}

export function findProductById(id: string): Produto | undefined {
  return produtos.find((produto) => produto.id === id);
}


export default produtos;